# Include the QtPyVCP default menubar.
{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: simple_tune
  version: v0.0.1
  author: My Name
  description: >
    Put a short description of your VCP here. This will be
    shown in the VCP Chooser when launching QtPyVCP with the
    --chooser option.


    Examples of what to included here:
      * VCP Features
      * Type of machine the VCP is for
      * Development status
      * Acknowledgments

data_plugins:
  status:
    kwargs:
      cycle_time: 75

    notifications:
        provider: qtpyvcp.plugins.notifications:Notifications
        kwargs:
          enabled: False

windows:

  mainwindow:
    # Specify the class to use for the VCP's mainwindow
    #   Format: package.module:class
    provider: simple_tune.mainwindow:MyMainWindow

    # Keyword arguments to pass when initializing the class.
    kwargs:
      # Specify the mainwindow menubar as the default.
      menu: ( default_menubar )
      # Specify the UI file to load the window layout from.
      ui_file: {{ file.dir }}/ui/mainwindow.ui
      # Specify a stylesheet to use only for mainwindow.
      stylesheet: null
      # Set the window title from from the date in the vcp section above.
      title: ( vcp.name ) ( vcp.version)

application:
  kwargs:
    # Specify the application wide stylesheet.
    stylesheet: {{ file.dir }}/ui/style.qss

settings:
    manual-touchoff.xy-offset:
        description: the offset used by the X and Y manual touch off. This would normally be the radius of a wiggler or equivalent
        default_value: 0.0
        persistent: true
        min_value: -50
        max_value: 50

    manual-touchoff.z-offset:
        description: the offset used by the Z manual touch off. Normally a guage block or guage pin
        default_value: 0.0
        persistent: true
        min_value: -50
        max_value: 50

    travel-test.travelDistanceTest:
        description: travel test distance
        default_value: 75.0
        persistent: true
        min_value: 0
        max_value: 600

    travel-test.travelDistanceTestFeed:
        description: feed rate for travel test
        default_value: 0.0
        persistent: true
        min_value: 0
        max_value: 1000

    travel-test.travelTestZlift:
        description: feed rate for travel test
        default_value: 0.0
        persistent: true
        min_value: 0
        max_value: 150
